name 'bootstrap'
maintainer 'Lou'
maintainer_email 'LouTheBrew@gmail.com'
license 'all_rights'
description 'bootstraps a node with stuff'
long_description 'bootstraps a node with stuff'
version '0.1.22'
depends 'poise'
depends 'hostname'
