name 'bootstrap'
maintainer 'Anaplan'
maintainer_email 'operations@anaplan.com'
license 'all_rights'
description 'bootstraps a node with stuff'
long_description 'bootstraps a node with stuff'
version '0.1.1'
depends 'poise'
depends 'hostname'
